accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
     path('signup/', views.SignUpView.as_view(), name='signup'),
     path('signup_success/', views.SignUpSuccessView.as_view(), name='signup_success'),

     #djangoのLoginViewをインスタンス化
     path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),

     #djangoのLogoutViewをインスタンス化
     path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

memoapp/urls.py
from django.urls import path
from . import views

#URLパターン逆引き用空間名
app_name = 'memo'

#URLパターン登録
urlpatterns = [
    #memoアプリへのアクセス
    path('', views.LogoutpageView.as_view(), name='logout_page'),
    path('index/', views.IndexView.as_view(), name='index'),
    path('create_memo/', views.CreateMemoView.as_view(), name='create_memo'),

    #メモ作成完了ページへのアクセス
    path('preserve_done/', views.PreserveSuccessView.as_view(), name='preserve_done'),
    
    #カテゴリ一覧ページ
    path('memo/<int:category>/', views.CategoryView.as_view(), name = 'memo_cat'),
    
    # 詳細ページ
    path('memo-detail/<int:pk>/', views.DetailView.as_view(), name = 'memo_detail'),

    # 投稿写真の削除
    path('memo/<int:pk>/delete/', views.MemoDeleteView.as_view(), name = 'memo_delete'),

    #メモ削除完了ページへのアクセス
    path('delete_done/', views.DeleteSuccessView.as_view(), name='delete_done'),

    #メモの編集ページ
    path('update_memo/<int:pk>/', views.UpdateMemoView.as_view(), name='update_memo'),
]

memoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    #memoapp.urlsへのURLパターン
    path('', include('memoapp.urls')),
    # accounts.urlsへのURLパターン
    path('', include('accounts.urls')),


    # パスワードリセットのためのURLパターン　<<< PasswordResetConfirmViewがプロジェクトのurls.pyを参照する >>>
    # パスワードリセット申し込みページ
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name = "password_reset.html"), name ='password_reset'),
    # メール送信完了ページ
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name = "password_reset_sent.html"), name ='password_reset_done'),
    # パスワードリセットページ
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name = "password_reset_form.html"), name ='password_reset_confirm'),
    # パスワードリセット完了ページ
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name = "password_reset_done.html"), name ='password_reset_complete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):
    pass

memoapp/models.py
from django.db import models
from accounts.models import CustomUser

# Create your models here.
class Category(models.Model):
    '''カテゴリ管理モデル
    '''
    title = models.CharField(verbose_name='カテゴリ', max_length=20)
    
    def __str__(self):
        '''オブジェクトを文字列に変換して返す{Returns(str):カテゴリ名}
        '''
        return self.title

class MemoPreserve(models.Model):
    '''メモデータ管理モデル
    '''
    #CustomUserモデル(のuser_id)と1対多の関係で結び付ける
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.CASCADE)
    #Categoryモデル(のtitle)と1対多の関係で結び付ける
    category = models.ForeignKey(Category, verbose_name='カテゴリ', on_delete=models.PROTECT)
    #タイトル用のフィールド
    title = models.CharField(verbose_name='タイトル', max_length=200)
    #メモ用のフィールド
    note = models.TextField(verbose_name='メモ')
    # 投稿日時のフィールド
    posted_at = models.DateTimeField(verbose_name='投稿日時', auto_now_add=True)
    
    def __str__(self):
        '''オブジェクトを文字列に変換して返す{Returns(str):投稿記事のタイトル}
        '''
        return self.title

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        # 連携するUserモデルを設定
        model = CustomUser
        # フォームで使用するフィールドを設定
        fields = ('username', 'email', 'password1', 'password2')

memoapp/forms.py
from django.forms import ModelForm
from .models import MemoPreserve

class MemoPreserveForm(ModelForm):
    class Meta:
        '''        
        Attributes:
          model: モデルのクラス
          fields: フォームで使用するモデルのフィールドを指定
        '''
        model = MemoPreserve
        fields = ['category', 'title', 'note']

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy

# Create your views here.
class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    template_name = "signup.html"
    #サインアップ完了後のリダイレクト先のURLパターン
    success_url = reverse_lazy('accounts:signup_success')

    def form_valid(self, form):
        # formオブジェクトのフィールドの値をデータベースに保存
        user = form.save()
        self.object = user
        # 戻り値はスーパークラスのform_valid()の戻り値(HttpResponseRedirect)
        return super().form_valid(form)

class SignUpSuccessView(TemplateView):
    template_name = "signup_success.html"

memoapp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, CreateView, DetailView, DeleteView, UpdateView
from django.urls import reverse_lazy
from .forms import MemoPreserveForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import MemoPreserve
from accounts.models import CustomUser

# Create your views here.
class LogoutpageView(TemplateView):
    template_name = 'base_logout.html'

class IndexView(ListView):
    template_name = 'index.html'
    paginate_by = 9

    def get_queryset(self):
        #ログインユーザーで絞り込み
        current_user = self.request.user.username
        user_data = CustomUser.objects.get(username=current_user)
        if user_data:
            queryset = MemoPreserve.objects.filter(user=user_data).all()
            queryset = queryset.order_by('-posted_at')
        return queryset

#アクセスをログインユーザーに限定　ログイン状態でなければsettings.pyのLOGIN_URLにリダイレクトされる
@method_decorator(login_required, name='dispatch')
class CreateMemoView(CreateView):
    '''メモ作成ページのビュー
    '''
    form_class = MemoPreserveForm
    template_name = "preserve_memo.html"
    success_url = reverse_lazy('memo:preserve_done')

    def form_valid(self, form):
        # commit=FalseにしてPOSTされたデータを取得
        postdata = form.save(commit=False)
        # 投稿ユーザーのidを取得してモデルのuserフィールドに格納
        postdata.user = self.request.user
        # 投稿データをデータベースに登録
        postdata.save()
        # 戻り値はスーパークラスのform_valid()の戻り値(HttpResponseRedirect)
        return super().form_valid(form)

@method_decorator(login_required, name='dispatch')
class PreserveSuccessView(TemplateView):
    '''作成完了ページのビュー
    '''
    template_name ='preserve_success.html'

@method_decorator(login_required, name='dispatch')
class CategoryView(ListView):
    '''カテゴリページのビュー
    '''
    template_name ='index.html'
    paginate_by = 9

    def get_queryset(self):
        #ログインユーザーとカテゴリのidで絞り込み
        current_user = self.request.user.username
        user_data = CustomUser.objects.get(username=current_user)
        category_id = self.kwargs['category']
        categories = MemoPreserve.objects.filter(user=user_data, category=category_id)
        categories = categories.order_by('-posted_at')
        return categories

@method_decorator(login_required, name='dispatch')
class DetailView(DetailView):
    '''詳細ページのビュー
    '''
    template_name ='detail.html'
    model = MemoPreserve

@method_decorator(login_required, name='dispatch')
class MemoDeleteView(DeleteView):
    '''レコードの削除を行うビュー
    '''
    model = MemoPreserve
    template_name ='memo_delete.html'
    success_url = reverse_lazy('memo:delete_done')

    def delete(self, request, *args, **kwargs):
      # スーパークラスのdelete()を実行
      return super().delete(request, *args, **kwargs)

@method_decorator(login_required, name='dispatch')
class DeleteSuccessView(TemplateView):
    '''削除完了ページのビュー
    '''
    template_name ='delete_success.html'

@method_decorator(login_required, name='dispatch')
class UpdateMemoView(UpdateView):
    model = MemoPreserve
    template_name = 'update_memo.html'
    form_class = MemoPreserveForm

    def get_success_url(self):
        return reverse_lazy('memo:memo_detail', kwargs={'pk':self.kwargs['pk']})

accounts/templates/login.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Log in</title>

    <link rel="icon" type="image/x-icon" href={% static 'assets/favicon.ico' %} />

    <!-- Bootstrap core CSSを読み込むコード -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {font-size: 1.125rem; text-anchor: middle; -webkit-user-select: none; -moz-user-select: none; user-select: none;}

      @media (min-width: 768px) {.bd-placeholder-img-lg {font-size: 3.5rem;}}
    </style>

    
    <link href={% static "css/signin.css" %} rel="stylesheet">
  </head>
  <body class="text-center">    
    <main class="form-signin">
      <!-- ユーザー名とパスワードが一致しない場合のメッセージ -->
      {% if form.errors %}
        <p style="color: red">ユーザー名とパスワードが一致しません。</p>
      {% endif %}
      <!-- ログインのフォームを配置 -->
      <form method="post">
        {% csrf_token %}
        <img class="mb-4" src={% static "img/site-logo.png" %} alt="" width="72" height="57">
        <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
        <!-- Usernameのラベル(非表示) -->
        <label for="Username" class="visually-hidden">ユーザー名</label>
        <!-- usernameの<input>タグを出力　name属性の値はLoginViewで定義されているフィールド名username -->
        <input type="text" name="username" id="id_username" maxlength="150" autocapitalize="none" autocomplete="username" class="form-control" placeholder="ユーザー名" required autofocus>
        <!-- Passwordのラベル(非表示) -->
        <label for="Password" class="visually-hidden">パスワード</label>
        <!-- passwordの<input>タグを出力　name属性の値はLoginViewで定義されているフィールド名password -->
        <input type="password" name="password" id="id_password" autocomplete="current-password" class="form-control" placeholder="パスワード" required autofocus>
        
        <!-- ログインボタンを配置 -->
            <input class="w-100 btn btn-lg btn-primary" type="submit" value="ログイン">
        
        <!-- パスワードリセットページのリンクテキスト -->
        <br><br>
        <p><a href="{% url 'password_reset' %}">パスワードを忘れましたか?</a><p>
        <!-- ログイン直後のリダイレクト先(トップページ)のURLパターンを設定 -->
        <input type="hidden" name="next" value="{% url 'memo:index' %}">
      </form>
    </main>   
  </body>
</html>

accounts/templates/logout.html
{% extends 'base.html' %}
{% block title %}Log out{% endblock %}

      {% block contents %}
      <!-- Bootstrapのグリッドシステム -->
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-4を入れる
               列の上下パディングはpy-4 -->
          <div class="col offset-4 py-4">

          <h3>ログアウトしました</h3>
          <!-- トップページのリンクテキスト -->
          <p><a href="{% url 'memo:logout_page' %}">トップページへ</a><p>
      {% endblock %}

accounts/templates/password_reset.html
{% extends 'base.html' %}
{% block title %}Reset password{% endblock %}

      {% block contents %}
      <!-- Bootstrapのグリッドシステム-->
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の上下パディングはpy-4-->
          <div class="col py-4">
            <hr>
            <h3>パスワードをリセットしますか?</h3>
            <p>
              登録済みのメールアドレスを入力してください。
              パスワードリセットのリンクを記載したメールをすぐにお届けします。
            </p>
            <br>
            <!-- メール送信のためのフォームを配置-->
            <form action="" method="POST" class="text-center">
              {% csrf_token %}
              <!-- formに格納されているインプットボックスとラベルを出力-->
              {{form}}
              <!-- 送信ボタン -->
              <input type="submit" value="メールを受け取る" /><br>
            </form>
            <br>
            <!-- トップページへのリンク-->
            <a href="{% url 'memo:index' %}">トップページへ</a>
            <hr>
          </dv>
        </dv>
      </dv>
      {% endblock %}

accounts/templates/password_reset_done.html
<!doctype html>
<html lang="ja">
  <head>
    <style>
      .pad{background-color: lavender; border: solid 2px; padding-top: 30px; padding-bottom: 50px; padding-left: 100px; margin-top: 50px; margin-right: 70px; margin-left: 70px;}
    </style>
  </head>

  <body>
    <div class="pad">
      <h2>パスワードがリセットされました。</h2>
      <p>
        Your Password has been set. You may go ahead and login
      </p>
      <br>
      <!-- トップページへのリンク-->
      <a href="{% url 'memo:index' %}">トップページへ</a>
    </div>
  </body>
</html>

accounts/templates/password_reset_sent.html
{% extends 'base.html' %}
{% block title %}Send password reset{% endblock %}

      {% block contents %}
      <!-- 水平線-->
      <hr>
      <!-- Bootstrapのグリッドシステム-->
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-2を入れる　列の上下パディングはpy-4-->
          <div class="col offset-2 py-4">
              <h5>パスワードのリセット手順をメールで送信しました。
                メールはすぐに届きます。</h5>
              <br>
              <h6>
                メールが届かない場合は、登録済みのメールアドレスであるかを
                確認し、迷惑メールフォルダーも確認してみてください。</h6>
              <br>
              <!-- トップページへのリンク-->
              <a "{% url 'memo:index' %}">トップページへ</a>
          </dv>
        </dv>
      </dv>
      {% endblock %}

accounts/templates/signup_success.html
{% extends 'base.html' %}
{% block title %}Registration Complete{% endblock %}

      {% block contents %}
      <!-- Bootstrapのグリッドシステム -->
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-4を入れる　列の上下パディングはpy-4 -->
          <div class="col offset-4 py-4">
            <h3>登録が完了しました</h3>
            <!-- ログインページのリンクテキスト -->
            <p><a href="{% url 'accounts:login' %}">ログインはこちら</a><p>
          </dv>
        </dv>
      </dv>
      {% endblock %}

memoapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <style>
            .bd-placeholder-img {
              font-size: 1.125rem;
              text-anchor: middle;
              -webkit-user-select: none;
              -moz-user-select: none;
              user-select: none;
            }
      
            @media (min-width: 768px) {
              .bd-placeholder-img-lg {
                font-size: 3.5rem;
              }
            }
        </style>    
    </head>

    <body>
        <div class="collapse bg-dark" id="navbarResponsive">
            <div class="container">
                <div class="row">
                    <div class="col-sm-4 offset-md-1 py-5">
                        <ul class="list-unstyled">
                            <!-- ナビゲーションメニュー-->
                            <!-- ログイン中のメニュー-->
                            <li><a href="{% url 'accounts:logout' %}"
                                   class="text-white">ログアウト</a></li>
                            <li><a href="{% url 'password_reset' %}"
                                   class="text-white">パスワードのリセット</a></li>
                            <li><a href="mailto:mro2423016@stu.o-hara.ac.jp"
                                   class="text-white">お問い合わせ</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- Navigation-->
        <nav class="navbar navbar-dark shadow-sm" id="mainNav">
            <div class="container px-4 px-lg-5">
                <!-- トップページへのリンク -->
                <a href="{% url 'memo:index' %}" 
                   class="navbar-brand d-flex align-items-center">
                    <!-- リンクテキスト -->
                    <strong>メモ帳</strong>
                </a>
                <!-- トグルボタン -->
                <button class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarResponsive"
                        aria-controls="navbarResponsive"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>メモ帳</h1>
                            <span class="subheading">memorandum</span>
                        </div>
                    </div>  
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main>
        {% block contents %}{% endblock %}
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="small text-center text-muted fst-italic">Copyright &copy; メモ帳</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

memoapp/templates/base_logout.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>メモ帳</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <style>
            .bd-placeholder-img {
              font-size: 1.125rem;
              text-anchor: middle;
              -webkit-user-select: none;
              -moz-user-select: none;
              user-select: none;
            }
      
            @media (min-width: 768px) {
              .bd-placeholder-img-lg {
                font-size: 3.5rem;
              }
            }
        </style>    
    </head>

    <body>
        <div class="collapse bg-dark" id="navbarResponsive">
            <div class="container">
                <div class="row">
                    <div class="col-sm-4 offset-md-1 py-5">
                        <ul class="list-unstyled">
                            <!-- ナビゲーションメニュー-->
                            <!-- ログアウト中 -->
                            <li><a href="{% url 'accounts:signup' %}"
                                class="text-white">サインアップ</a></li>
                            <li><a href="{% url 'accounts:login' %}"
                                   class="text-white">ログイン</a></li>
                            <li><a href="mailto:mro2423016@stu.o-hara.ac.jp"
                                   class="text-white">お問い合わせ</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- Navigation-->
        <nav class="navbar navbar-dark shadow-sm" id="mainNav">
            <div class="container px-4 px-lg-5">
                <!-- トグルボタン -->
                <button class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarResponsive"
                        aria-controls="navbarResponsive"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>メモ帳</h1>
                            <span class="subheading">memorandum</span>
                        </div>
                    </div>  
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main>
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <!-- 内容 -->
                        <h1 class="fw-light">メモ帳</h1>
                        <p>
                            <!-- ナビゲーションボタン -->
                            <!-- ログアウト中 -->
                            <a href="{% url 'accounts:signup' %}" class="btn btn-primary my-2">今すぐサインアップ</a>
                            <a href="{% url 'accounts:login' %}" class="btn btn-secondary my-2">登録済みの方はログイン</a>
                        </p>
                    </div>
                </div>
            </div>            
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="small text-center text-muted fst-italic">Copyright &copy; メモ帳</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

memoapp/templates/detail.html
{% extends 'base.html' %}
{% block title %}Memo Detail{% endblock %}

      {% block contents %}
      <br>
      <div class="container">
        <!-- 行 -->
        <div class="row">
          <!-- 列 -->
          <div class="col offset-3">
            <!-- タイトル -->
            <h2>{{object.title}}</h2>
            <!-- メモ -->
            <p>{{object.note}}</p>
            <br>
            <!-- 投稿日時 -->
            <p>{{object.posted_at}}に作成</p>
            <!-- 削除ボタン -->
            <a href="{% url 'memo:memo_delete' object.pk %}" class="btn btn-primary my-2">削除する</a>
            <!-- 編集ボタン -->
            <a href="{% url 'memo:update_memo' object.pk %}" class="btn btn-primary my-2">編集する</a>
          </dv>
        </dv>
      </dv>
      {% endblock %}

memoapp/templates/index.html
{% extends 'base.html' %}
{% block title %}メモ帳{% endblock %}
    {% block contents %}

    {% include 'memo_title.html' %}

    {% include 'memo_list.html' %}

    {% endblock %}

memoapp/templates/memo_list.html
<div class="album py-5 bg-light">
    <div class="container">
        <!-- 行要素 -->
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <!-- レコードを1行ずつ取り出す -->
            {% for record in object_list %}
            <!-- 列要素 -->
            <div class="col">
                <div class="card shadow-sm">
                    <!-- タイトルとボタンを出力するブロック -->
                    <div class="card-body">
                        <p class="card-text">
                            {{record.title}}
                        </p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <!-- 詳細ページ -->
                                <button type="button"
                                        class="btn btn-sm btn-outline-primary"onclick="location.href='{% url 'memo:memo_detail' record.pk %}'">閲覧</button>
                                <!-- カテゴリ表示 -->
                                <button type="button"
                                        class="btn btn-sm btn-outline-primary"onclick="location.href='{% url 'memo:memo_cat' category=record.category.id %}'">{{record.category.title}}一覧</button>
                                <!-- 編集ページ -->
                                <button type="button"
                                        class="btn btn-sm btn-outline-primary"onclick="location.href='{% url 'memo:update_memo' record.pk %}'">編集</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

memoapp/templates/memo_title.html
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- 内容 -->
            <h1 class="fw-light">メモ帳</h1>
            <p>
                <!-- ナビゲーションボタン -->
                {% if user.is_authenticated %}
                <!-- ログイン中 -->
                <a href="{% url 'memo:create_memo' %}" class="btn btn-primary my-2">メモ作成</a>
                <a href="{% url 'accounts:logout' %}" class="btn btn-secondary my-2">ログアウト</a>
                {% else %}
                <!-- ログアウト中 -->
                <a href="{% url 'accounts:signup' %}" class="btn btn-primary my-2">今すぐサインアップ</a>
                <a href="{% url 'accounts:login' %}" class="btn btn-secondary my-2">登録済みの方はログイン</a>
                {% endif %}
            </p>
        </div>
    </div>
</div>